plugins {
    id 'java'
    id 'maven-publish'
    id 'groovy-gradle-plugin'
}

allprojects {
    java.sourceCompatibility = JavaVersion.VERSION_17

    repositories {
        mavenLocal()
        maven {
            url = uri('https://repo.maven.apache.org/maven2/')
        }
        mavenCentral()
    }
}

subprojects {
    plugins.apply('java')
    plugins.apply('maven-publish')
    plugins.apply('groovy-gradle-plugin')

    dependencies {
        ["annotationProcessor", "compileOnly", "testAnnotationProcessor", "testCompileOnly"]
                .forEach { conf -> add(conf, "org.projectlombok:lombok:1.18.38") }

        implementation 'org.apache.logging.log4j:log4j-core:2.24.3'

        testImplementation platform('org.junit:junit-bom:5.12.1')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }
}
