plugins {
    id 'java'
    id 'maven-publish'
}

allprojects {
    java.sourceCompatibility = JavaVersion.VERSION_1_8

    repositories {
        mavenLocal()
        maven {
            url = uri('https://repo.maven.apache.org/maven2/')
        }
        mavenCentral()
    }

}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    dependencies {
        ["annotationProcessor", "compileOnly", "testAnnotationProcessor", "testCompileOnly"]
                .forEach { conf -> add(conf, "org.projectlombok:lombok:1.18.38") }

        implementation 'org.apache.logging.log4j:log4j-core:2.18.0'

        testImplementation platform('org.junit:junit-bom:5.10.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}
