package dev.eltonsandre.caesium.gui;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.io.File;

public class MainPanel extends JPanel {

    protected JTextField inputField;
    protected JButton inJarButton;
    protected JButton outJarButton;
    protected JTextField outputField;
    protected JComboBox<String> applicationTypeComboBox;
    protected JComboBox<String> dictionaryComboBox;
    private JPanel contentPanel;
    protected JCheckBox noOverrideInputCheck;
    protected JCheckBox noOverrideOutputCheck;

    private String currentProfile = "user.home";

    protected MainPanel() {
        init();
    }

    private void init() {
        inJarButton.setIcon(Icons.loadIconSvgByTheme("menu-open"));

        FileFilter jarFileFilter = new FileNameExtensionFilter("Jar Files", "jar");
        inJarButton.addInputMethodListener(new InputMethodListener() {
            @Override
            public void inputMethodTextChanged(final InputMethodEvent event) {
                System.out.println("inputMethodTextChanged");
            }

            @Override
            public void caretPositionChanged(final InputMethodEvent event) {
                System.out.println("caretPositionChanged");
            }
        });
        inJarButton.addActionListener(l -> {
            JFileChooser chooser = new JFileChooser(currentProfile);
            chooser.setFileFilter(jarFileFilter);
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int response = chooser.showOpenDialog(inJarButton);

            if (response == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                currentProfile = file.getAbsolutePath();
                inputField.setText(currentProfile);
            }
        });

        outJarButton.setIcon(Icons.loadIconSvgByTheme("menu-open"));
        outJarButton.addActionListener(l -> {
            JFileChooser chooser = new JFileChooser(currentProfile);

            int response = chooser.showOpenDialog(outJarButton);

            if (response == JFileChooser.APPROVE_OPTION) {
                File file = chooser.getSelectedFile();
                currentProfile = file.getAbsolutePath();
                outputField.setText(currentProfile);
            }
        });

        applicationTypeComboBox.addItem("self-contained");
        applicationTypeComboBox.addItem("spigot plugin");

        dictionaryComboBox.addItem("abc");
        dictionaryComboBox.addItem("ABC");
        dictionaryComboBox.addItem("III");
        dictionaryComboBox.addItem("123");
        dictionaryComboBox.addItem("Wack");
        dictionaryComboBox.setSelectedIndex(3);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(7, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Input");
        contentPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPanel.add(spacer1, new GridConstraints(6, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Output");
        contentPanel.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        inputField = new JTextField();
        contentPanel.add(inputField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        inJarButton = new JButton();
        inJarButton.setText("");
        contentPanel.add(inJarButton, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outJarButton = new JButton();
        outJarButton.setText("");
        contentPanel.add(outJarButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outputField = new JTextField();
        contentPanel.add(outputField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Application type");
        contentPanel.add(label3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        applicationTypeComboBox = new JComboBox();
        contentPanel.add(applicationTypeComboBox, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Dictionary");
        contentPanel.add(label4, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        dictionaryComboBox = new JComboBox();
        contentPanel.add(dictionaryComboBox, new GridConstraints(5, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noOverrideInputCheck = new JCheckBox();
        noOverrideInputCheck.setText("No Override");
        contentPanel.add(noOverrideInputCheck, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        noOverrideOutputCheck = new JCheckBox();
        noOverrideOutputCheck.setSelected(false);
        noOverrideOutputCheck.setText("No Override");
        contentPanel.add(noOverrideOutputCheck, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
