plugins {
    id 'java'
}

group = 'dev.eltonsandre'
version = '1.0.10'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.ow2.asm:asm-tree:9.3',
            'org.ow2.asm:asm-commons:9.3',

            'net.sf.jopt-simple:jopt-simple:5.0.4',

            'com.google.guava:guava:33.3.1-jre',
            'javax.xml.bind:jaxb-api:2.3.1'
}

test {
    useJUnitPlatform()
}
