package dev.sim0n.caesium.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import dev.sim0n.caesium.PreRuntime;

import javax.swing.*;
import java.awt.*;
import java.io.File;

public class ClassPathPanel extends JPanel {

    private JTextField classPathField;
    private JButton addButton;
    private JButton removeButton;
    private JPanel contentPanel;
    private JList<String> classPathList;

    protected DefaultListModel<String> classPathListModel;

    private String currentProfile = "user.home";

    public ClassPathPanel() {
        init();
    }

    void init() {
        classPathListModel = new DefaultListModel<>();
        PreRuntime.classPaths.forEach(classPathListModel::addElement);

        classPathList.setModel(classPathListModel);
        addButton.setToolTipText("Add class path");
        addButton.setIcon(Icons.loadIconSvgByTheme("add"));
        addButton.addActionListener(e -> {
            if (classPathField.getText().length() > 1) {
                String path = classPathField.getText();
                if (!addClasspath(path)) {
                    JOptionPane.showMessageDialog(contentPanel, "Could not locate Classpath.", "Caesium Classpath",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                final JFileChooser chooser = new JFileChooser(currentProfile);
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                chooser.setMultiSelectionEnabled(true);
                int result = chooser.showOpenDialog(classPathField);

                if (result == 0) {
                    currentProfile = chooser.getSelectedFile().getParent();
                    File[] libs = chooser.getSelectedFiles();
                    for (File lib : libs) {
                         addClasspath(lib.toString());
                    }
                }
            }
        });

        removeButton.setToolTipText("Remove classPath");
        removeButton.setIcon(Icons.loadIconSvgByTheme("remove"));
        removeButton.addActionListener(e ->
                classPathList.getSelectedValuesList()
                        .forEach(dependency -> {
                            PreRuntime.classPaths.remove(dependency);
                            classPathListModel.removeElement(dependency);
                        }));
    }

    protected boolean addClasspath(final String path) {
        File file = new File(path);
        if (file.exists()) {
            PreRuntime.classPaths.add(path);
            if (!classPathListModel.contains(path)) {
                classPathListModel.addElement(path);
            }
            classPathField.setText(null);
            return true;
        }
        return false;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        classPathField = new JTextField();
        contentPanel.add(classPathField, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        addButton = new JButton();
        addButton.setText("");
        contentPanel.add(addButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeButton = new JButton();
        removeButton.setText("");
        contentPanel.add(removeButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPanel.add(panel1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        classPathList = new JList();
        scrollPane1.setViewportView(classPathList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
